language: go
go_import_path: github.com/baidu/easyfaas

sudo: true

go:
  - 1.16

script:
  - echo "start to build and test easyfaas"
  - make test
  - make
  - echo "finish"

after_success:
  - bash <(curl -s https://codecov.io/bash)
